version: '3'

# 系统配置
application:
    env: debug  # 合法选项 "" (默认为空 = debug ) "debug" "release" "test"
    host: localhost
    port: 8088
    public_path:
    doamin: localhost # 设置 set-cookie httpOnly=true 使用，能有效防止 csrf 攻击
# 数据库配置
mysql:
    host: 101.132.127.139
    port: 3306
    user: root
    pwd: yinaini.
    db: mi
    prefix:
    max_idle: 10
    max_active: 10
# redis配置
redis :
    host: localhost
    port: 6379
    password:
    db: 0
    pool_size: 100
# 日志配置
log:
    path: ./log
    level: info # 合法选项 "panic" "fatal" "error" "warn" "warning" "info" "debug" "trace"
# rbac 权限配置
casbin:
    path:
# 验证码配置
captcha:
    length: 4
    width: 150
    height: 50
    #  str: 234567890abcdefghjkmnpqrstuvwxyz
    str: 123456789
    font:
        - wqy-microhei.ttc
    noise: 100
    line: 3
# json web token 配置
jwt:
    key: bfgdiojhnpbwfsfa23/*-/*-/sgdeasdg4sd6+0@%!
    exp_time: 100 #小时
#七牛云配置
qiniuyun:
    accessKey: aDgkfcB_ysJMkoY91w4hlb-Cf4EQkc3KzC8jSlNf
    secretKey: 8qeDeC-n-9hH0xrdh9Ualftgi0YcJuVwQ_WzPBPK
    bucket: go-mi
    server: http://qwhu0mnc1.hn-bkt.clouddn.com/
